### ISSUE TITLE
Usage via Plots.jl

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPluto/PlutoPlotly.jl#28]
I find the syntax of using PlotlyJS directly quite bad. Is it possible to wrap this in Plots.jl somehow?

**Comment by disberd** [comment]
What do you mean by wrap this in Plots?

**Comment by KronosTheLate** [comment]
Allow Plots.jl to use PlutoPlotly as a backend, so that the user can produce PlutoPlot objects with Plots.jl syntax.

**Comment by disberd** [comment]
While I wouldn't be against it, I gave up with Plots in favor of directly using Plotly (PlotlyJS at the time) because the public plotly API of Plots is seriously lagging behind what is capable directly by using the plotly library.

I think the idea behind Plots is commendable but I think you soon find yourself finding limitations in what you can do via Plots as opposed to using directly the backend package.

For this reason I never delved into Plots internal and I wouldn't want to put the effort into this myself considering that you would miss out on a lot of functionalities you could get by using directly this package (to comply with the Plots API).

**Comment by KronosTheLate** [comment]
Right, that makes a lot of sense. I guess using Plotly just fiels foreign to me, but I did get somewhat used to it yesterday. I think we can close this.
